services:
  accounts:
    image: "ponaliprakash/account-service:v1"
    container_name: account_ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - banksnetwork
  cards:
    image: "ponaliprakash/card-service:v1"
    container_name: cards_ms
    ports:
      - "8070:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - banksnetwork
  loans:
    image: "ponaliprakash/loan-service:v1"
    container_name: loans_ms
    ports:
      - "8090:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - banksnetwork
networks:
  banksnetwork:
    driver: bridge



